apiVersion: v1
kind: Service
metadata:
  name: simple-node-app
  namespace: test-app
spec:
  selector:
    app: simple-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
