helm:
  parameters:
  - name: image.name
    value: us-docker.pkg.dev/test-argo-poc/application/app
    forcestring: true
  - name: image.tag
    value: 6fa7c88c-4f2a-41c5-b6fa-fc8cbade1aca
    forcestring: true
